### ISSUE TITLE
ezmomi status fails when certain column values are None

### ISSUE THREAD

**Issue by mchlumsky** [snobear/ezmomi#84]
ezmomi status --extra fails when certain column values are None

What happens:
$ ezmomi status --name server_name --extra
Traceback (most recent call last):
  File "/home/mchlumsky/Envs/ezmomi/bin/ezmomi", line 4, in <module>
    cli.cli()
  File "/home/mchlumsky/Envs/ezmomi/lib/python2.7/site-packages/ezmomi/cli.py", line 30, in cli
    ez.status()
  File "/home/mchlumsky/Envs/ezmomi/lib/python2.7/site-packages/ezmomi/ezmomi.py", line 527, in status
    self.print_as_table(status_to_print)
  File "/home/mchlumsky/Envs/ezmomi/lib/python2.7/site-packages/ezmomi/ezmomi.py", line 604, in print_as_table
    column_len = len(row[column])
TypeError: object of type 'NoneType' has no len()

**Comment by mchlumsky** [comment]
Proposed fix:
https://github.com/snobear/ezmomi/pull/85

**Comment by snobear** [comment]
Fixed ^.
