### ISSUE TITLE
Python 3 pip install not working due to print statement

### ISSUE THREAD

**Issue by cgkades** [snobear/ezmomi#93]
Unable to pip install in python 3 due to what looks like a python2 print statement.

```
╰─➤ python --version; pip --version                                                                                
Python 3.7.1
pip 18.1 from /Users/brett.yoakum/python/py3/lib/python3.7/site-packages/pip (python 3.7)
```

```
╰─➤  pip install ezmomi
Collecting ezmomi
  Using cached https://files.pythonhosted.org/packages/35/fd/8ba25866ff30f915a0609f1f553f79ae3e81088ee34c521736006f23c73d/ezmomi-6.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4v/d6697ns10hxd9rx5bnlns4s40000gq/T/pip-install-yalzzg55/ezmomi/setup.py", line 9
        print "Unable to import ezmomi/version.py. Exiting."
                                                           ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unable to import ezmomi/version.py. Exiting.")?
```

**Comment by snobear** [comment]
Closing per fix ^.
